# Site settings
title: "Rosas do Mato"
author: "Ismael"
description: "Miscelânea Digital — Jardim de Rosas"
keywords: "Poesia, Islã, Islamismo, Árabe, Persa, Turco, Artes, Traduções, Blog, Pessoal"
biography: "Não sou ninguém importante — Apenas uma alma"
colophon: "MMXXIII, Ismael Sinjaro"

baseurl: ""
url: "http://hugosereno.eu"

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
